### PR TITLE
move react to peerDependencies to allow use with react 16.x

### PR DESCRIPTION
**Pull request by jharris4**

### CODE REVIEW

**Comment by jharris4** [comment]
the direct dependency of react-loaders on react 15.x.x means it cannot be used with react 16.x.x.

Would love to see this merged so I can continue using react-loaders with React 16.

**Comment by jharris4** [comment]
As a temporary workaround, I'm using this in my package.json:

```
"react-loaders": "git://github.com/jharris4/react-loaders.git#bdc8268454a87ac245a9519005619dbdede5d1fd"
```

And it's working fine with react 16

**Comment by scragg0x** [comment]
@jonjaques Please pull and publish asap

**Comment by jharris4** [comment]
Thanks for merging, hopefully you can release a new version soon... ;-)

**Comment by jonjaques** [comment]
Unfortunately this broke the demo, so stand by while I fix that.

**Comment by jharris4** [comment]
ah, anything I can do to help?

**Comment by jonjaques** [comment]
Thanks for the offer, just needed to upgrade react-bootstrap (prolly unnecessary for demo, but I'm lazy).

Landed in react-loaders@2.6.0

**Comment by jharris4** [comment]
Ah yeah, I just looked and the version of react-bootstrap that you were using was still trying to use React.PropTypes which was completely removed in React 16...

**Comment by jharris4** [comment]
FYI 2.6.0 is up on npm, but you seem to have forgotten to push the changes to github ;-)

**Pull request merged**
